---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "django-app"
  namespace: "default"
  labels:
    app: "django-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "django-app"
  template:
    metadata:
      labels:
        app: "django-app"
    spec:
      containers:
      - name: "django-app"
        image: "gcr.io/revreplatform-220422/django-app:v2"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "django-app-hpa"
  namespace: "default"
  labels:
    app: "django-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "django-app"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
