# Generated by Django 2.0.4 on 2018-05-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('estimate', models.IntegerField()),
                ('neighbourhood', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
