# Generated by Django 2.0.5 on 2018-06-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homevalue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
